services:
  redis:
    image: redis
    volumes:
      - redis_data:/data
    expose:
      - 6379
  livekit:
    image: livekit/livekit-server
    command: --dev --redis-host localhost:6379
    network_mode: host
  sip:
    image: livekit/sip
    network_mode: host
    environment:
      SIP_CONFIG_BODY: |
        api_key: 'devkey'
        api_secret: 'secret'
        ws_url: 'ws://localhost:7880'
        redis:
          address: 'localhost:6379'
        sip_port: 5060
        rtp_port: 10000-20000
        use_external_ip: true
        logging:
          level: debug
volumes:
  redis_data: