// Code generated by "stringer -type HealthStatus -trimprefix Health"; DO NOT EDIT.

package stats

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[HealthOK-0]
	_ = x[HealthNotStarted-1]
	_ = x[HealthStopped-2]
	_ = x[HealthUnderLoad-3]
	_ = x[HealthDisabled-4]
}

const _HealthStatus_name = "OKNotStartedStoppedUnderLoadDisabled"

var _HealthStatus_index = [...]uint8{0, 2, 12, 19, 28, 36}

func (i HealthStatus) String() string {
	if i < 0 || i >= HealthStatus(len(_HealthStatus_index)-1) {
		return "HealthStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _HealthStatus_name[_HealthStatus_index[i]:_HealthStatus_index[i+1]]
}
